### ISSUE TITLE
Can't locate object method "new" via package "Device::TPlink::SmartHome::Direct"

### ISSUE THREAD

**Issue by Heptite** [verlin/Device-TPLink#2]
As the title says, it doesn't provide new(), so the entire module fails to be of use.

**Comment by verlin** [comment]
Do you have Moose installed? In this module, new() comes from the:

use Moose;

statement on line 4. See https://metacpan.org/pod/distribution/Moose/lib/Moose/Manual/Construction.pod for more information.

**Comment by Heptite** [comment]
Yes, it is installed, and up to date.

**Comment by verlin** [comment]
Did you install the module from CPAN, or are you attempting to build it yourself? Do you mind sharing the code that you're using?

**Comment by verlin** [comment]
I just grabbed a copy of the repo, built, and installed it under Perl 5.26.1 on Ubuntu 18.04 and I'm not seeing any issues. The following script works with no problems:

#!/usr/bin/perl

use strict;
use Device::TPLink::SmartHome::Direct;
my $foo = Device::TPLink::SmartHome::Direct->new(port => "5000", addr => "192.168.1.100");

print $foo->port;
print $foo->addr;

**Comment by Heptite** [comment]
I must apologize for the noise. If you look closely at the title of the issue report, I had a typo that existed in my code. (TPlink as opposed to TPLink. I don't know why Perl didn't throw an error.)

Everything works fine now. Thank you.

**Comment by verlin** [comment]
Glad you got it working!
